name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'qp/src/**'
      - 'qp/tests/**'
      - 'qp/Cargo.toml'
      - 'qp-postgres/src/**'
      - 'qp-postgres/tests/**'
      - 'qp-postgres/Cargo.toml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'qp/src/**'
      - 'qp/tests/**'
      - 'qp/Cargo.toml'
      - 'qp-postgres/src/**'
      - 'qp-postgres/tests/**'
      - 'qp-postgres/Cargo.toml'

jobs:
  codecov:
    name: CodeCov
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Install nightly toolchain and llvm-tools-preview component
        run: rustup toolchain install nightly --component llvm-tools-preview && rustup default nightly

      - name: Install grcov
        run: cargo install grcov

      - name: Test
        env:
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
          RUSTFLAGS: -Zinstrument-coverage
        run: cargo test

      - name: Generate coverage
        run: grcov --ignore-not-existing --binary-path ./target/debug/ -o lcov.info -s . .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: lcov.info
          fail_ci_if_error: true

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: rustfmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        run: cargo test
