name: Quick Pool

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/qp.yml'
      - 'qp/src'
      - 'qp/tests'
      - 'qp/Cargo.toml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/qp.yml'
      - 'qp/src'
      - 'qp/tests'
      - 'qp/Cargo.toml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache crates
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('qp/Cargo.toml') }}

      - name: rustfmt
        run: cargo fmt -p qp -- --check

      - name: Clippy
        run: cargo clippy -p qp -- -D warnings

